const VERSION="20260703-v2";
const MODEL_SOURCES=["./models","https://cdn.jsdelivr.net/gh/justadudewhohacks/face-api.js@0.22.2/weights"];
const FALLBACK={packages:[
{code:"P1",min:18,max:39,gender:"general",color:"#2d9b32",name:{ar:"باقة الشباب",en:"Youth Package"},range:{ar:"18-39 سنة",en:"18-39 years"},tags:{ar:["مؤشر كتلة الجسم","ضغط الدم","الدهون"],en:["BMI","Blood pressure","Lipids"]},reason:{ar:"للنساء من عمر 30 سنة فما فوق تضاف مسحة عنق الرحم.",en:"For women aged 30+, cervical smear is added."},checks:{ar:["مؤشر كتلة الجسم","ضغط الدم","الدهون"],en:["Body Mass Index","Blood pressure","Lipid profile"]}},
{code:"P2",min:40,max:44,gender:"general",color:"#078ca0",name:{ar:"باقة الأربعينات 1",en:"Forties Package 1"},range:{ar:"40-44 سنة",en:"40-44 years"},tags:{ar:["مؤشر كتلة الجسم","ضغط الدم","الدهون"],en:["BMI","Blood pressure","Lipids"]},reason:{ar:"للنساء تضاف أشعة الثدي ومسحة عنق الرحم.",en:"For women, mammogram and cervical smear are added."},checks:{ar:["مؤشر كتلة الجسم","ضغط الدم","الدهون"],en:["Body Mass Index","Blood pressure","Lipid profile"]}},
{code:"P3",min:45,max:49,gender:"general",color:"#0757b8",name:{ar:"باقة الأربعينات 2",en:"Forties Package 2"},range:{ar:"45-49 سنة",en:"45-49 years"},tags:{ar:["السكري","القولون","دهون وضغط"],en:["Diabetes","Colon","Lipids/BP"]},reason:{ar:"للنساء تضاف أشعة الثدي ومسحة عنق الرحم.",en:"For women, mammogram and cervical smear are added."},checks:{ar:["مؤشر كتلة الجسم","ضغط الدم","الدهون","السكري","القولون"],en:["Body Mass Index","Blood pressure","Lipid profile","Diabetes screening","Colon screening"]}},
{code:"M1",min:50,max:65,gender:"male",color:"#552e91",name:{ar:"باقة صحة الرجل",en:"Men's Health Package"},range:{ar:"50-65 سنة",en:"50-65 years"},tags:{ar:["صحة الرجل","السكري والدهون","القولون والبروستاتا"],en:["Men's health","Diabetes/Lipids","Colon/Prostate"]},reason:{ar:"الفحوصات المقترحة حسب باقة صحة الرجل.",en:"Recommended screenings according to the men's health package."},checks:{ar:["مؤشر كتلة الجسم","ضغط الدم","الدهون","السكري","القولون","فحص البروستاتا"],en:["Body Mass Index","Blood pressure","Lipid profile","Diabetes screening","Colon screening","Prostate screening"]}},
{code:"F1",min:50,max:65,gender:"female",color:"#d72773",name:{ar:"باقة صحة المرأة",en:"Women's Health Package"},range:{ar:"50-65 سنة",en:"50-65 years"},tags:{ar:["صحة المرأة","أشعة الثدي","مسحة عنق الرحم"],en:["Women's health","Mammogram","Cervical smear"]},reason:{ar:"الفحوصات المقترحة حسب باقة صحة المرأة.",en:"Recommended screenings according to the women's health package."},checks:{ar:["مؤشر كتلة الجسم","ضغط الدم","الدهون","السكري","القولون","أشعة الثدي","مسحة عنق الرحم"],en:["Body Mass Index","Blood pressure","Lipid profile","Diabetes screening","Colon screening","Mammogram","Cervical smear"]}},
{code:"G1",min:66,max:75,gender:"general",color:"#d89116",name:{ar:"باقة العمر الذهبي",en:"Golden Age Package"},range:{ar:"66-75 سنة",en:"66-75 years"},tags:{ar:["العمر الذهبي","متابعة شاملة","حسب الاستحقاق"],en:["Golden age","Comprehensive","Eligibility"]},reason:{ar:"بعض الفحوصات تعتمد على الاستحقاق وتاريخ الفحوصات السابقة.",en:"Some screenings depend on eligibility and previous screening history."},checks:{ar:["مؤشر كتلة الجسم","ضغط الدم","الدهون","السكري","القولون"],en:["Body Mass Index","Blood pressure","Lipid profile","Diabetes screening","Colon screening"]}}
]};
const TR={ar:{lang:"English",rangeError:"الخدمة مخصصة للأعمار من 18 إلى 75 سنة.",staffAlert:"يرجى التوجه للموظف الموجود في البوث لمعرفة التفاصيل.",cameraLoading:"يتم طلب إذن الكاميرا...",cameraReady:"الكاميرا جاهزة. ضع وجهك داخل القلب.",cameraFail:"تعذر فتح الكاميرا. يمكنك معرفة الباقة مباشرة.",faceGood:"الوجه واضح",faceMissing:"لم يظهر الوجه بوضوح",faceNear:"قرب وجهك قليلاً",faceFar:"ابتعد قليلاً",faceCenter:"ضع وجهك داخل القلب",tryAgain:"ثم حاول مرة أخرى.",years:"سنة",female:"أنثى",male:"ذكر",visits:"الزيارات",direct:"مسار مباشر",cameraUse:"استخدام الكاميرا",cameraFailCount:"فشل الكاميرا",estimates:"العمر الظاهري",results:"نتائج الباقات",cleared:"تم مسح الإحصاءات المحلية."},en:{lang:"العربية",rangeError:"This service is for ages 18 to 75.",staffAlert:"Please approach the booth staff for details.",cameraLoading:"Requesting camera permission...",cameraReady:"Camera is ready. Place your face inside the heart.",cameraFail:"Could not open the camera. You can find the package directly.",faceGood:"Face is clear",faceMissing:"Face is not clear",faceNear:"Move closer",faceFar:"Move back slightly",faceCenter:"Center your face",tryAgain:"then try again.",years:"years",female:"Female",male:"Male",visits:"Visits",direct:"Direct path",cameraUse:"Camera use",cameraFailCount:"Camera failures",estimates:"Age estimates",results:"Package results",cleared:"Local analytics cleared."}};
const I18N={en:{service:"Early chronic disease screening",welcomeTitle:"Scan the QR",welcomeLead:"Find your preventive package based on your real age and gender. The apparent-age feature is optional and for awareness only.",startJourney:"Start",directPackage:"Find my package directly",slogan:"A simple step... for better health",privacyEyebrow:"Your privacy matters",beforeCamera:"Before opening the camera",noSaveTitle:"No photo is saved",noSaveText:"Your photo is not stored or sent to a server.",funOnlyTitle:"For entertainment only",funOnlyText:"Apparent age is not a medical assessment and does not affect the package.",realAgeTitle:"Decision by real age",realAgeText:"The package depends on real age, gender, and screening history.",openCamera:"Agree and open camera",skipCamera:"Find my package without camera",cameraTitle:"Place your face inside the heart",cameraLead:"Smile... start the reassurance journey",cameraPreparing:"Preparing...",estimateAge:"Estimate apparent age",manualNoCamera:"Find my package without camera",processingTitle:"Taking several readings",processingLead:"A few seconds for a more stable result...",funResult:"Entertainment result",apparentTitle:"Approximate apparent age",funOnlyShort:"For fun only.",decisionNotice:"The health decision depends on real age and gender, not on the photo.",next:"Next",realInfoEyebrow:"To select your package",realInfoTitle:"Your real information",realAge:"Real age",gender:"Gender",showPackage:"Show my preventive package",basedOn:"Based on your real age and gender",yourPackage:"Your suitable package",recommendedChecks:"Recommended screenings",eligibilityNote:"Final eligibility depends on the electronic health record and previous screening history.",staffCard:"Show staff card",restart:"Restart",askStaff:"Ask staff",healthCard:"Health reassurance card",forStaff:"For staff review",ageLabel:"Age",genderLabel:"Gender",requiredChecks:"Required screenings",eligibilityNoteStaff:"Final eligibility depends on the electronic health record and previous screening history.",backToResult:"Back to result",newTest:"New test",analyticsTitle:"Device analytics",packageCounts:"Package counts",analyticsNote:"These numbers are stored only on this device and do not include photos, names, or individual ages.",clearAnalytics:"Clear local analytics"}};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let lang=localStorage.getItem("mirat_lang")||"ar", packages=FALLBACK.packages, stream=null, models=false, cam=false, timer=null, idle=null, quality=null, last=null, taps=0;
function t(k){return TR[lang][k]||k}
function applyLang(){document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr";if(lang==="en")$$("[data-i18n]").forEach(e=>{const v=I18N.en[e.dataset.i18n];if(v)e.textContent=v});else location.hash==="#no-reload";$$("[data-i18n=female]").forEach(e=>e.textContent=t("female"));$$("[data-i18n=male]").forEach(e=>e.textContent=t("male"));const b=$("#langToggle");if(b)b.textContent=t("lang");$("#realAge")?.setAttribute("placeholder",lang==="ar"?"أدخل عمرك":"Enter your age")}
async function loadPackages(){try{const r=await fetch(`./packages.json?v=${VERSION}`,{cache:"no-store"});if(r.ok){const j=await r.json();if(Array.isArray(j.packages))packages=j.packages}}catch(e){console.warn(e)}}
function data(){try{return JSON.parse(localStorage.getItem("mirat_analytics")||"{}")}catch{return {}}}
function save(a){localStorage.setItem("mirat_analytics",JSON.stringify(a))}
function track(k,code){const a=data();a[k]=(a[k]||0)+1;if(code){a.packages=a.packages||{};a.packages[code]=(a.packages[code]||0)+1}save(a)}
function show(name){$$(".screen").forEach(s=>s.classList.toggle("active",s.dataset.screen===name));if(name==="analytics")renderStats();clearTimeout(timer);if(["package-result","staff-card","apparent-result"].includes(name))timer=setTimeout(restart,60000);resetIdle()}
function resetIdle(){clearTimeout(idle);idle=setTimeout(restart,120000)}
function setQ(msg,state="neutral"){$("#qualityBadge").textContent=msg;$("#qualityBadge").dataset.state=state}
function status(msg){$("#cameraStatus").textContent=msg}
function stop(){clearInterval(quality);quality=null;if(stream){stream.getTracks().forEach(x=>x.stop());stream=null}cam=false}
async function loadModels(){if(models)return true;if(!window.faceapi)return false;for(const src of MODEL_SOURCES){try{await faceapi.nets.tinyFaceDetector.loadFromUri(src);await faceapi.nets.ageGenderNet.loadFromUri(src);models=true;return true}catch(e){console.warn("model",src)}}return false}
async function openCamera(){track("cameraUse");show("camera");$("#estimateBtn").disabled=true;status(t("cameraLoading"));try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user"},audio:false});$("#cameraVideo").srcObject=stream;await $("#cameraVideo").play();cam=true;const ok=await loadModels();$("#estimateBtn").disabled=false;status(ok?t("cameraReady"):"AI fallback");if(ok)watchFace();else setQ("AI fallback","warning")}catch(e){track("cameraFail");setQ(t("cameraFail"),"warning");status(t("cameraFail"))}}
const opts=()=>new faceapi.TinyFaceDetectorOptions({inputSize:224,scoreThreshold:.45});
async function qFace(){if(!cam||!models||!window.faceapi)return {ok:false,msg:"AI fallback",state:"warning"};const faces=await faceapi.detectAllFaces($("#cameraVideo"),opts());if(!faces.length)return {ok:false,msg:t("faceMissing"),state:"warning"};if(faces.length>1)return {ok:false,msg:lang==="ar"?"وجه واحد فقط":"One face only",state:"warning"};const b=faces[0].box,v=$("#cameraVideo"),w=v.videoWidth||1,h=v.videoHeight||1,a=b.width*b.height/(w*h),cx=b.x+b.width/2,cy=b.y+b.height/2;if(a<.08)return {ok:false,msg:t("faceNear"),state:"warning"};if(a>.48)return {ok:false,msg:t("faceFar"),state:"warning"};if(cx<w*.25||cx>w*.75||cy<h*.2||cy>h*.78)return {ok:false,msg:t("faceCenter"),state:"warning"};return {ok:true,msg:t("faceGood"),state:"good"}}
function watchFace(){setQ(lang==="ar"?"نبحث عن الوجه...":"Looking for a face...");quality=setInterval(async()=>{try{const q=await qFace();setQ(q.msg,q.state)}catch{setQ(t("faceCenter"))}},900)}
function manualAge(){return 33+Math.round(Math.random()*9)}
async function readAge(){if(!cam||!models||!window.faceapi)return manualAge();const d=await faceapi.detectSingleFace($("#cameraVideo"),opts()).withAgeAndGender();return d&&d.age?d.age:null}
async function estimate(){if(cam&&models){const q=await qFace();if(!q.ok){setQ(q.msg,q.state);status(`${q.msg} ${t("tryAgain")}`);return}}show("processing");$("#progressFill").style.width="0%";const a=[];for(let i=0;i<8;i++){const r=await readAge();if(Number.isFinite(r))a.push(r);$("#progressFill").style.width=`${Math.round((i+1)*12.5)}%`;await new Promise(x=>setTimeout(x,170))}const s=(a.length?a:[manualAge()]).sort((x,y)=>x-y),m=s.length>4?s.slice(1,-1):s,avg=m.reduce((x,y)=>x+y,0)/m.length;const rr=Math.round(avg);$("#apparentAgeRange").textContent=`${Math.max(18,rr-2)}-${Math.min(90,rr+2)}`;track("estimates");stop();show("apparent-result")}
function pick(age,g){return packages.find(p=>age>=p.min&&age<=p.max&&(p.gender==="general"||p.gender===g))}
function checks(p,age,g){let c=[...(p.checks?.[lang]||p.checks?.ar||[])];const add=(ar,en)=>c.push(lang==="ar"?ar:en);if(p.code==="P1"&&g==="female"&&age>=30)add("مسحة عنق الرحم","Cervical smear");if(["P2","P3"].includes(p.code)&&g==="female"){add("أشعة الثدي","Mammogram");add("مسحة عنق الرحم","Cervical smear")}if(p.code==="G1"){if(g==="male"&&age<=70)add("فحص البروستاتا","Prostate screening");if(g==="female")add("فحوصات المرأة حسب الاستحقاق","Women's screenings according to eligibility")}return [...new Set(c)]}
function list(el,items){el.replaceChildren(...items.map(x=>{const li=document.createElement("li");li.textContent=x;return li}))}
function showPackage(p,age,g){const c=checks(p,age,g);last={p,age,g,c};$("#packageCard").style.setProperty("--pkg",p.color);$("#packageCode").textContent=p.code;$("#packageName").textContent=p.name[lang]||p.name.ar;$("#packageRange").textContent=p.range[lang]||p.range.ar;const tags=p.tags[lang]||p.tags.ar;$("#packageTagOne").textContent=tags[0]||"";$("#packageTagTwo").textContent=tags[1]||"";$("#packageTagThree").textContent=tags[2]||"";$("#packageReason").textContent=p.reason[lang]||p.reason.ar;list($("#packageChecks"),c);track("results",p.code);stop();show("package-result")}
function staff(){if(!last)return;const {p,age,g,c}=last;$("#staffCard").style.setProperty("--pkg",p.color);$("#staffPackageCode").textContent=p.code;$("#staffPackageName").textContent=p.name[lang]||p.name.ar;$("#staffPackageRange").textContent=p.range[lang]||p.range.ar;$("#staffAge").textContent=lang==="ar"?`${age} سنة`:`${age} years`;$("#staffGender").textContent=g==="female"?t("female"):t("male");list($("#staffChecks"),c);show("staff-card")}
function renderStats(){const a=data(),grid=$("#analyticsGrid"),items=[["visits",a.visits||0],["direct",a.direct||0],["cameraUse",a.cameraUse||0],["cameraFailCount",a.cameraFail||0],["estimates",a.estimates||0],["results",a.results||0]];grid.replaceChildren(...items.map(([k,v])=>{const d=document.createElement("div");d.className="analytics-card";d.innerHTML=`<strong>${v}</strong><span>${t(k)}</span>`;return d}));const p=a.packages||{};list($("#analyticsPackages"),Object.keys(p).sort().map(k=>`${k}: ${p[k]}`))}
function direct(){track("direct");show("real-info")}
function restart(){stop();last=null;$("#realInfoForm")?.reset();$("#formError").textContent="";$("#apparentAgeRange").textContent="--";show("welcome")}
function bind(){document.addEventListener("click",e=>{const go=e.target.closest("[data-go]"),back=e.target.closest("[data-back]");if(go)show(go.dataset.go);if(back){stop();show(back.dataset.back)}});["click","touchstart","keydown"].forEach(ev=>document.addEventListener(ev,resetIdle,{passive:true}));$("#startExperienceBtn").onclick=()=>show("consent");$("#directPackageBtn").onclick=direct;$("#skipCameraBtn").onclick=direct;$("#manualFromCameraBtn").onclick=direct;$("#openCameraBtn").onclick=openCamera;$("#estimateBtn").onclick=estimate;$("#showStaffCardBtn").onclick=staff;$("#staffCardBackBtn").onclick=()=>show("package-result");$("#restartBtn").onclick=restart;$("#staffCardRestartBtn").onclick=restart;$("#staffBtn").onclick=()=>alert(t("staffAlert"));$("#langToggle").onclick=()=>{lang=lang==="ar"?"en":"ar";localStorage.setItem("mirat_lang",lang);applyLang();if(last)showPackage(last.p,last.age,last.g)};$("#adminTap").onclick=()=>{taps++;setTimeout(()=>taps=0,1400);if(taps>=5){taps=0;show("analytics")}};$("#clearAnalyticsBtn").onclick=()=>{localStorage.removeItem("mirat_analytics");renderStats();alert(t("cleared"))};$("#realInfoForm").onsubmit=e=>{e.preventDefault();const age=+$("#realAge").value,g=new FormData(e.currentTarget).get("gender"),p=pick(age,g);$("#formError").textContent="";if(!p){$("#formError").textContent=t("rangeError");return}showPackage(p,age,g)}}
window.addEventListener("pagehide",stop);
(async()=>{track("visits");applyLang();await loadPackages();bind();resetIdle()})();
